### ISSUE TITLE
Trouble in running baseline results 

### ISSUE THREAD

**Issue by TanyaChowdhury** [UKPLab/lrec2018-live-blog-corpus#2]
On executing 
`python summarize/baseline.py -d guardian -l english
`
the program tends to use the in built  python2.7/site-packages/rouge/rouge.py.
Was it intended this way?

**Comment by avineshpvs** [comment]
We have provided the ROUGE package within our repository. Looks like they have conflicting names and the python is picking up your installed rouge package.
